# Generated by Django 5.0.7 on 2024-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='about_us', verbose_name='Картинка')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('title2', models.CharField(max_length=50, verbose_name='Почему мы')),
                ('title3', models.CharField(max_length=50, verbose_name='Наши преимущества')),
                ('text2', models.TextField(verbose_name='Преимушество текст')),
                ('title4', models.CharField(max_length=50, verbose_name='Наши услуги')),
                ('text4', models.TextField(verbose_name='Услуги текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
