# Generated by Django 5.0.7 on 2024-08-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='text3',
            field=models.TextField(default=1, verbose_name='Преимушество текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text2',
            field=models.TextField(verbose_name='Почему мы текст'),
        ),
    ]
